In [18]:
import torch 

In [19]:
x = torch.rand(3, 3)
x

tensor([[0.7167, 0.3948, 0.8547],
        [0.2246, 0.7470, 0.5405],
        [0.9346, 0.5444, 0.2184]])

In [20]:
x[1, 1]

tensor(0.7470)

In [21]:
y = x.view(-1, 1)

In [22]:
y

tensor([[0.7167],
        [0.3948],
        [0.8547],
        [0.2246],
        [0.7470],
        [0.5405],
        [0.9346],
        [0.5444],
        [0.2184]])

In [23]:
a = torch.ones(5)
b = a.numpy()
a + b

tensor([2., 2., 2., 2., 2.])

In [1]:
import wrds




In [2]:
db = wrds.Connection()

WRDS recommends setting up a .pgpass file.
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done


In [3]:
db.list_libraries().sort()

In [4]:
db.list_libraries()

['aha_sample',
 'ahasamp',
 'auditsmp',
 'auditsmp_all',
 'bank',
 'bank_all',
 'bank_premium_samp',
 'banksamp',
 'block',
 'block_all',
 'boardex_trial',
 'boardsmp',
 'bvd_amadeus_trial',
 'bvd_bvdbankf_trial',
 'bvd_orbis_trial',
 'bvdsamp',
 'calcbench_trial',
 'calcbnch',
 'cboe',
 'cboe_all',
 'cboe_sample',
 'cboesamp',
 'ciq',
 'ciq_capstrct',
 'ciq_common',
 'ciq_keydev',
 'ciq_pplintel',
 'ciqsamp',
 'ciqsamp_capstrct',
 'ciqsamp_common',
 'ciqsamp_keydev',
 'ciqsamp_pplintel',
 'ciqsamp_ratings',
 'ciqsamp_transactions',
 'ciqsamp_transcripts',
 'cisdmsmp',
 'columnar',
 'comp',
 'comp_bank',
 'comp_bank_daily',
 'comp_execucomp',
 'comp_filings',
 'comp_global',
 'comp_global_daily',
 'comp_na_annual_all',
 'comp_na_daily_all',
 'comp_na_monthly_all',
 'comp_segments_hist',
 'comp_segments_hist_daily',
 'compa',
 'compb',
 'compg',
 'compm',
 'compsamp',
 'compsamp_all',
 'compsamp_snapshot',
 'compseg',
 'contrib',
 'contrib_as_filed_financials',
 'contrib_ceo_turnover',


In [5]:
libraries = db.list_libraries()
db.list_tables(library='crsp_a_stock')

['dse',
 'dseall',
 'dsedelist',
 'dsedist',
 'dseexchdates',
 'dsenames',
 'dsenasdin',
 'dseshares',
 'dsf',
 'dsf_v2',
 'dsfhdr',
 'dsi',
 'dsiy',
 'inddlyseriesdata',
 'indfamilyinfohdr',
 'indmthseriesdata',
 'indseriesinfohdr',
 'metacalendarperiod',
 'metacolumncoverage',
 'metacolumninfo',
 'metaexchangecalendar',
 'metafileinfo',
 'metaflagcoverage',
 'metaflaginfo',
 'metaflagtype',
 'metaiteminfo',
 'metasiztociz',
 'mse',
 'mseall',
 'msedelist',
 'msedist',
 'mseexchdates',
 'msenames',
 'msenasdin',
 'mseshares',
 'msf',
 'msf_v2',
 'msfhdr',
 'msi',
 'msiy',
 'saz_agg_ann',
 'saz_agg_ann_legacy',
 'saz_agg_mth',
 'saz_agg_mth_legacy',
 'saz_agg_qtr',
 'saz_agg_qtr_legacy',
 'saz_del',
 'saz_del_legacy',
 'saz_dind',
 'saz_dind_legacy',
 'saz_dis',
 'saz_dis_legacy',
 'saz_dp_dly',
 'saz_dp_dly_legacy',
 'saz_ds_dly',
 'saz_ds_dly_legacy',
 'saz_hdr',
 'saz_hdr_legacy',
 'saz_indhdr',
 'saz_indhdr_legacy',
 'saz_mdel',
 'saz_mdel_legacy',
 'saz_mind',
 'saz_mind_legacy',


In [ ]:
data = db.get_table(library='crsp_a_stock', table='wrds_dsfv2_query')